/**
 * Hydro Manifest Types
 * 
 * These types match the JSON manifest generated by the cdk_export function in deploy_graph_containerized_ecs.rs
 */

export interface HydroBuildConfig {
  project_dir: string;
  target_dir: string;
  bin_name: string;
  package_name: string;
  features: string[];
}

export interface HydroLocationKey {
  idx: number;
  version: number;
}

export interface HydroPortInfo {
  port: number;
}

export interface HydroProcess {
  build: HydroBuildConfig;
  location_key: HydroLocationKey;
  ports: Record<string, HydroPortInfo>;
  task_family: string;
}

export interface HydroCluster {
  build: HydroBuildConfig;
  location_key: HydroLocationKey;
  ports: Record<string, HydroPortInfo>;
  default_count: number;
  task_family_prefix: string;
}

export interface HydroManifest {
  processes: Record<string, HydroProcess>;
  clusters: Record<string, HydroCluster>;
}
