#!/usr/bin/env bash
set -e

mkdir -p fuzz

export CARGO_BUILD_TARGET=$(rustc -vV | grep 'host:' | awk '{print $2}')
export RUSTFLAGS="$RUSTFLAGS -C prefer-dynamic -Copt-level=3 -Ccodegen-units=1 -Cpasses=sancov-module -Cllvm-args=-sanitizer-coverage-inline-8bit-counters -Cllvm-args=-sanitizer-coverage-level=4 -Cllvm-args=-sanitizer-coverage-pc-table -Cllvm-args=-sanitizer-coverage-trace-compares"
export BOLERO_FUZZER="libfuzzer"

cargo test --lib ${@:2} --nocapture --test-threads=1
