//! Rung 0 of the quorum→consensus ladder: the **quorum certificate mint**.
//!
//! # A quorum is a stability certificate
//!
//! A fact attested by `k` **distinct** cluster members survives any crash
//! pattern that kills fewer than `k` of them: some attestor is still alive and
//! still holds the fact. Choosing `k = F + 1` (where `F` bounds crashes, the
//! same `F` as [`with_crashable_cluster`](hydro_lang::sim::flow::SimFlow::with_crashable_cluster))
//! makes the fact *crash-durable under the fault model*: [`Durable<F>`] is the
//! certificate of that upgrade.
//!
//! This is deliberately **proof territory, not type territory**. Eventual
//! consistency is inferred by structural induction over the dataflow graph —
//! value-abstract, local, symmetric. A quorum claim is none of those things:
//! it counts *distinct member identities inside the payloads* against a
//! cardinality of the deployment. The type system therefore cannot *derive*
//! [`Durable`]; what it can do is make the certificate **unforgeable** (only
//! this mint constructs it) and **propagable** (a certificate, once minted, is
//! a stable fact — monotone, EC-friendly, exactly like a `Joined` event). The
//! trusted residue is concentrated here, in one audited combinator, so that
//! protocols built on top (URB, ABD, synod) carry zero assertions of their own.
//!
//! # The mint's obligations (the `manual_proof!` ledger)
//!
//! 1. **Durability** (carried by the [`Durable`] type): a certificate for fact
//!    `f` exists only if `threshold` distinct members attested `f`. With
//!    `threshold > F` over **static membership** (deploy-time `ClusterIds`,
//!    fixed `N`), any crash pattern within budget leaves a correct attestor.
//!    This is a fault-model fact — pigeonhole over runtime sets — not a
//!    consistency label, and no mechanical oracle checks it here; the crash
//!    simulator attacks it instead (see the URB separation tests).
//! 2. **Determinism through the slice** (the `assert_has_consistency_of`
//!    below): attestations are deduplicated and persisted, the count per fact
//!    is monotone, the threshold is fixed, and the fired-set ensures each fact
//!    certifies at most once — so the certificate set is a deterministic
//!    function of the (eventually consistent) attestation set, independent of
//!    batch boundaries. EC in, EC out.
//!
//! # Static membership only, on purpose
//!
//! There is deliberately no version of this mint over a live
//! [`MembershipView`](crate::ec_inference_demos::fan_out::MembershipView):
//! "a majority of a set that is still growing" is not a well-posed claim.
//! Quorum systems over dynamic membership require *versioned* views (epochs) —
//! this combinator is the concrete forcing function for that tier (research
//! agenda §4 item 4).
//!
//! # Known gaps (honest ledger)
//!
//! - **Unforgeability is by convention, not privacy.** Staged (`q!`) code is
//!   expanded outside this module, so the constructor cannot be truly private
//!   yet; it is `#[doc(hidden)]` and screamingly named instead. Real sealing
//!   requires promoting the mint into `hydro_lang`'s trusted base (the same
//!   promotion path as `fan_out`'s completeness premise).
//! - **Certificates are local.** `Durable` is deliberately not `Serialize`:
//!   shipping a certificate to another location would let the receiver
//!   "deserialize a forgery." A transportable certificate needs its own design
//!   (attestor set + re-verification, or a trusted channel type).

use std::hash::Hash;

use hydro_lang::live_collections::stream::{ExactlyOnce, NoOrder, Retries};
use hydro_lang::location::member_id::TaglessMemberId;
use hydro_lang::location::{Location, MemberId};
use hydro_lang::prelude::*;
use serde::{Deserialize, Serialize};

/// Timestamp / ballot: `(round, writer)` lexicographic. `writer` is the
/// minting member's id, so distinct writers never produce equal values and
/// max-merge never has to tie-break on payloads. ABD uses these as register
/// timestamps; synod uses them as ballots — they are the same object.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct Ts {
    pub round: u64,
    pub writer: TaglessMemberId,
}

/// A fact certified crash-durable: at least `threshold` distinct members of
/// the (static) cluster attested it, so it survives any crash pattern killing
/// fewer than `threshold` members.
///
/// Only [`quorum`] mints these (see the module docs for the enforcement
/// caveat). Deliberately not `Serialize` — see the module docs.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Durable<F> {
    fact: F,
}

impl<F> Durable<F> {
    /// **Not public API.** The mint's constructor; called only from staged
    /// code generated by [`quorum`]. Calling this anywhere else forges a
    /// durability certificate the fault model has not earned.
    #[doc(hidden)]
    pub fn __mint_called_only_by_the_quorum_combinator(fact: F) -> Self {
        Durable { fact }
    }

    /// The certified fact.
    pub fn fact(&self) -> &F {
        &self.fact
    }

    /// Unwrap the certified fact.
    pub fn into_fact(self) -> F {
        self.fact
    }
}

/// **The quorum certificate mint.** Counts *distinct* attestors per fact and
/// emits a [`Durable`] certificate exactly once, when the count crosses
/// `threshold`.
///
/// The observer can be any location: a cluster member assembling echoes (URB)
/// or a client `Process` assembling replica acks (ABD). `acks` carries
/// `(fact, attestor)` pairs; duplicate attestations (retries, re-echoes) are
/// deduplicated before counting, so a repeating member cannot forge a quorum.
/// `threshold` must be chosen against the cluster's deploy-time size and
/// fault budget by the caller: `F + 1` for durability, `N/2 + 1` for
/// intersection (rung 2+).
pub fn quorum<'a, F, L, L2, R>(
    threshold: usize,
    acks: Stream<(F, MemberId<L2>), L, Unbounded, NoOrder, R>,
) -> Stream<Durable<F>, L, Unbounded, NoOrder, ExactlyOnce>
where
    F: Clone + Eq + Hash + 'a,
    L: Location<'a>,
    L2: 'a,
    R: Retries,
{
    // Distinctness: one attestation per (fact, member), ever. This is what
    // makes the count below a count of *members*, not of messages.
    let distinct_acks = acks.unique();

    let certified = sliced! {
        let new_acks = use::batch(distinct_acks, nondet!(
            /// Attestations not yet at quorum are persisted across slices and
            /// facts fire exactly once, so the certificate set is independent
            /// of batch boundaries (mint obligation 2 in the module docs).
        ));

        // Attestations for facts that have not yet fired.
        let mut pending = use::state_null::<Stream<(F, MemberId<L2>), _, Bounded, NoOrder>>();
        // Facts that have already fired: nothing fires twice.
        let mut fired = use::state_null::<Stream<F, _, Bounded, NoOrder>>();

        let current = pending.chain(new_acks);

        // Count distinct attestors per fact (inputs are globally deduplicated).
        let count_per_fact = current.clone().into_keyed().fold(
            q!(|| 0usize),
            q!(|count, _attestor| {
                *count += 1;
            }, commutative = manual_proof!(/** counting is commutative */)),
        );

        let reached = count_per_fact
            .filter(q!(move |count| *count >= threshold))
            .keys();

        // Fire each fact at most once, ever.
        let newly_certified = reached.clone().filter_not_in(fired.clone());

        // Persist: drop attestations for fired facts (their job is done, and
        // late attestations must not re-accumulate toward a second firing);
        // remember everything that ever fired.
        pending = current.anti_join(reached);
        fired = fired.chain(newly_certified.clone());

        newly_certified
            .map(q!(|fact| Durable::__mint_called_only_by_the_quorum_combinator(fact)))
    };

    certified.assert_has_consistency_of(manual_proof!(
        /// Mint obligation 2 (module docs): the certificate set is a
        /// deterministic, monotone function of the attestation *set* —
        /// attestations are deduplicated and persisted, counts only grow, the
        /// threshold is fixed, and the fired-set makes each fact certify at
        /// most once. Since the input attestation stream is eventually
        /// consistent (all live members converge on the same set), all live
        /// members converge on the same certificate set: EC in, EC out.
    ))
}

/// A covering certificate: `threshold` distinct members answered this
/// request, so (by quorum intersection, when `threshold` is a majority) the
/// aggregate dominates every fact that was `Durable` before the request.
///
/// Only [`covering_quorum`] mints these (same enforcement caveat as
/// [`Durable`]). Unlike `Durable`, a covering's *content* is authored by the
/// schedule — WHICH majority answered — so this mint deliberately does
/// **not** restore a consistency label through its slice: certificate
/// existence is deterministic, certificate content is honest nondeterminism.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Covering<A> {
    aggregate: A,
}

impl<A> Covering<A> {
    /// **Not public API.** See [`Durable`]'s constructor caveat.
    #[doc(hidden)]
    pub fn __mint_called_only_by_the_covering_combinator(aggregate: A) -> Self {
        Covering { aggregate }
    }

    /// The aggregate the covering read observed.
    pub fn aggregate(&self) -> &A {
        &self.aggregate
    }

    /// Unwrap the observed aggregate.
    pub fn into_aggregate(self) -> A {
        self.aggregate
    }
}

/// **The covering-read mint.** Per request key, counts distinct responders
/// and folds the running max-by-[`Ts`] of their payloads in ONE accumulator
/// (so the certificate's content is atomically consistent with its trigger),
/// firing exactly once when the count crosses `threshold`.
///
/// `responses` carries `(key, (responder, payload))`; exact duplicates are
/// deduplicated, and responders must answer each key at most once (both
/// current consumers guarantee this structurally: replicas/acceptors answer
/// each query exactly once over an exactly-once channel).
///
/// The aggregation is fixed to max-by-`Ts` over `Option<(Ts, X)>` — the
/// shape shared by register timestamps and ballots. Generalizing to a
/// caller-supplied lattice awaits a clean way to pass proof-annotated
/// combiners through a library function; this covers the current family.
///
/// The `nondet!` inside is load-bearing and justified: which
/// `threshold`-subset answers first picks WHICH covering read this is, and
/// any majority intersects every write quorum, so any covering's max
/// dominates every completed durable fact.
pub fn covering_quorum<'a, K, X, L, L2, R>(
    threshold: usize,
    responses: Stream<(K, (MemberId<L2>, Option<(Ts, X)>)), L, Unbounded, NoOrder, R>,
) -> Stream<(K, Covering<Option<(Ts, X)>>), L::DropConsistency, Unbounded, NoOrder, ExactlyOnce>
where
    K: Clone + Eq + Hash + 'a,
    X: Clone + Eq + Hash + 'a,
    L: Location<'a>,
    L2: 'a,
    R: Retries,
{
    let distinct = responses.unique();

    let covered = sliced! {
        let new_resps = use::batch(distinct, nondet!(
            /// Which majority answers first (and where batch boundaries
            /// fall) picks WHICH covering read this is. Any majority is a
            /// valid covering: it intersects every write quorum, so its max
            /// dominates every completed durable fact.
        ));

        let mut pending = use::state_null::<Stream<(K, (MemberId<L2>, Option<(Ts, X)>)), _, Bounded, NoOrder>>();
        let mut fired = use::state_null::<Stream<K, _, Bounded, NoOrder>>();

        let current = pending.chain(new_resps);

        let per_key = current.clone().into_keyed().fold(
            q!(|| (0usize, None)),
            q!(|(count, max): &mut (usize, Option<(Ts, _)>), (_responder, payload)| {
                *count += 1;
                if let Some((ts, x)) = payload {
                    if max.as_ref().map(|(m, _)| *m < ts).unwrap_or(true) {
                        *max = Some((ts, x));
                    }
                }
            }, commutative = manual_proof!(
                /** counting is commutative; max by the total Ts order is
                commutative (writer ids make ties impossible). */
            )),
        );

        let reached = per_key
            .filter(q!(move |(count, _max)| *count >= threshold))
            .entries()
            .map(q!(|(key, (_count, max))| (key, max)));

        let newly = reached.clone().anti_join(fired.clone());

        pending = current.anti_join(reached.map(q!(|(key, _)| key)));
        fired = fired.chain(newly.clone().map(q!(|(key, _)| key)));

        newly
    };

    covered.map(q!(|(key, max)| {
        (key, Covering::__mint_called_only_by_the_covering_combinator(max))
    }))
}

#[cfg(test)]
mod tests {
    use hydro_lang::live_collections::stream::{ExactlyOnce, NoOrder};
    use hydro_lang::location::MemberId;
    use hydro_lang::location::cluster::EventualConsistency;
    use hydro_lang::prelude::*;

    use super::quorum;

    /// The mint's functional contract, exhaustively at n=1: certificates fire
    /// exactly at the distinct-attestor threshold, duplicates from one member
    /// do not forge a quorum, and nothing ever fires twice.
    #[test]
    fn quorum_counts_distinct_attestors_and_fires_once() {
        let mut flow = FlowBuilder::new();
        let cluster = flow.cluster::<()>();

        let (ack_send, acks) =
            cluster.sim_input::<(u32, MemberId<()>), NoOrder, ExactlyOnce>();

        let out_recv = quorum(2, acks.assert_has_consistency_of::<Cluster<'_, (), EventualConsistency>>(manual_proof!(
            /// Test harness: the sim input plays an EC attestation stream.
        )))
        .map(q!(|cert| cert.into_fact()))
        .sim_cluster_output();

        flow.sim()
            .skip_consistency_assertions()
            .with_cluster_size(&cluster, 1)
            .exhaustive(async || {
                ack_send.send_many_unordered([
                    // Fact 7: the same member attesting twice is ONE attestor.
                    (0, (7u32, MemberId::from_raw_id(0))),
                    (0, (7u32, MemberId::from_raw_id(0))),
                    // Fact 9: two distinct attestors -> certificate; a third
                    // attestor must not fire it again.
                    (0, (9u32, MemberId::from_raw_id(0))),
                    (0, (9u32, MemberId::from_raw_id(1))),
                    (0, (9u32, MemberId::from_raw_id(2))),
                ]);

                let got: Vec<u32> = out_recv.collect_sorted(0).await;
                assert_eq!(
                    got,
                    vec![9],
                    "exactly one certificate, for the fact with 2 distinct attestors"
                );
            });
    }
}
