[profile.default]
slow-timeout = { terminate-after = 10 } # terminate after 10 intervals of (default: `period = "60s"`).
default-filter = "not (package(hydro_test) & kind(bench))"

[test-groups]
serial-integration = { max-threads = 1 }

# TODO(inline): deadlock_detector disabled (intra-tick cycles)
# [[profile.default.overrides]]
# filter = 'binary(deadlock_detector)'
# test-group = 'serial-integration'

[[profile.default.overrides]]
filter = 'binary(two_pc_hf)'
test-group = 'serial-integration'

[[profile.default.overrides]]
filter = 'binary(kvs)'
test-group = 'serial-integration'

[[profile.default.overrides]]
filter = 'binary(kvs_replicated)'
test-group = 'serial-integration'

[[profile.default.overrides]]
filter = 'binary(echo_local)'
test-group = 'serial-integration'

[[profile.default.overrides]]
filter = 'test(fuzz_with_cargo_sim)'
threads-required = 'num-test-threads'

[[profile.default.overrides]]
filter = 'test(test_distributed_echo_example_docker)'
threads-required = 'num-test-threads'

# under heavy CPU load, Maelstrom is flaky when multiple nodes are launched
[[profile.default.overrides]]
filter = 'test(maelstrom::broadcast::tests::broadcast_3b_maelstrom)'
threads-required = 'num-test-threads'

[[profile.default.overrides]]
filter = 'test(maelstrom::broadcast::tests::broadcast_3c_maelstrom)'
threads-required = 'num-test-threads'
