#[cfg(feature = "tokio")]
pub mod compartmentalized_paxos;
#[cfg(feature = "tokio")]
pub mod compute_pi;
pub mod kv_replica;
pub mod many_to_many;
pub mod map_reduce;
#[cfg(feature = "tokio")]
pub mod paxos;
#[cfg(feature = "tokio")]
pub mod paxos_bench;
#[cfg(feature = "tokio")]
pub mod paxos_log_bench;
#[cfg(feature = "tokio")]
pub mod paxos_with_client;
pub mod simple_cluster;
#[cfg(feature = "tokio")]
pub mod two_pc;
#[cfg(feature = "tokio")]
pub mod two_pc_bench;
